source 'http://rubygems.org'
ruby '1.9.3'

gem 'rails', '3.1.0'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

group :development, :test do
	gem 'sqlite3' , '1.3.8'
	gem 'rspec-rails', '2.13.1'
end

#gem 'bootstrap-sass'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier' , '>= 1.3.0'
end

gem 'jquery-rails' , '3.0.4'
gem 'jbuilder', '~> 1.2'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  # Pretty printed test output
  gem 'selenium-webdriver', '2.35.1'
  gem 'capybara', '2.1.0'
  gem 'turn', :require => false
end

#group :production do
#	gem 'pg', '0.15.1'
#	gem 'rails_12factor', '0.0.2'
#end